permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Jun
  email: j.sheerly@gmail.com
  link: http://junyin.github.io
  weibo: http://weibo.com/yansu0711
  github: http://github.com/junyin

# 站点信息
title: jun's blog
description: jun's personal blog
url: http://junyin.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://yansu-uploads.stor.sinaapp.com/imgs/gavatar.png
favicon: http://yansu-uploads.stor.sinaapp.com/imgs/favicon.ico

# google analytics 设置
ga:
  id: UA-54767140-1
  url: junyin.github.io

# disqus 设置
disqus:
  shortname: jun_yin

# 主题设置，自动激活某个标签
active: notes

# 首页除了最新文章外显示分类
cates: 
  - OpenGL

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
